[settings]
experimental = true

[env]
_.path = "{{config_root}}/.tasks"

[tools]
gh = "2.97.0"
go = "1.26.6"
hadolint = "2.14.0"
jq = "1.8.2"
lefthook = "2.1.11"
shellcheck = "0.11.0"
yq = "4.53.6"
zizmor = "1.29.0"

[hooks]
postinstall = ["lefthook install"]
